from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import inch, cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfgen import canvas
from pydantic import BaseModel
import os
import sys
import uuid
import json
import requests
from datetime import date

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from main import call_deepseek

router = APIRouter()

TEMPLATES = {
    "business_report": {"sections": ["Executive Summary", "Introduction", "Analysis", "Key Findings", "Recommendations", "Conclusion"], "has_header": True, "has_footer": True, "has_table_of_contents": True},
    "research_paper": {"sections": ["Abstract", "Introduction", "Literature Review", "Methodology", "Results", "Discussion", "Conclusion", "References"], "has_header": True, "has_footer": True, "has_table_of_contents": True},
    "proposal": {"sections": ["Overview", "Problem Statement", "Proposed Solution", "Timeline", "Budget", "Team", "Conclusion"], "has_header": True, "has_footer": True, "has_table_of_contents": False},
    "resume": {"sections": ["Contact", "Summary", "Experience", "Education", "Skills", "Projects"], "has_header": False, "has_footer": False, "has_table_of_contents": False},
    "invoice": {"sections": ["Header", "Client Info", "Items", "Total", "Terms"], "has_header": True, "has_footer": True, "has_table_of_contents": False},
    "general": {"sections": ["Introduction", "Main Content", "Details", "Summary", "Conclusion"], "has_header": True, "has_footer": True, "has_table_of_contents": False},
}

OUTPUT_DIRECTORY = "output"
os.makedirs(OUTPUT_DIRECTORY, exist_ok=True)


class PDFRequest(BaseModel):
    prompt: str
    document_type: str


def generate_pdf_content(prompt: str, document_type: str, template: dict) -> dict:
    system_prompt = f"""You are an expert document designer and writer.
Generate professional beautiful document content AND choose the perfect design theme.

Analyze the user prompt and automatically select the best colors and design.

Return ONLY valid JSON with this exact structure:
{{
  "title": "Document title",
  "subtitle": "Document subtitle",
  "author": "AOS - AI Operating System",
  "date": "2024",
  "design": {{
    "primary_color": "Choose a relevant professional hex color: business #1e3a8a, technology #1a1a2e, creative #7c3aed, health #065f46, finance/legal #1e293b, education #1d4ed8, marketing #be185d, science #0f172a, environment #14532d, food/lifestyle #92400e",
    "accent_color": "Choose a complementary bright readable hex color",
    "secondary_color": "Slightly lighter version of primary",
    "background_color": "#ffffff",
    "text_color": "#1f2937",
    "font_style": "Choose: modern OR classic OR elegant OR bold",
    "layout_style": "Choose: corporate OR creative OR minimal OR academic"
  }},
  "sections": [{{
    "heading": "Section heading",
    "content": "Detailed professional paragraph with minimum 4 sentences. Make it comprehensive and valuable.",
    "subsections": [{{"heading": "Subsection heading", "content": "Subsection detailed content"}}],
    "bullet_points": ["Detailed point 1 with explanation", "Detailed point 2 with explanation", "Detailed point 3 with explanation", "Detailed point 4 with explanation"],
    "has_table": false,
    "table_data": []
  }}],
  "footer_text": "Confidential - Generated by AOS AI Operating System",
  "color_theme_name": "Name of the chosen theme like Ocean Blue or Royal Purple"
}}

Rules:
1. Choose colors that match the document topic perfectly.
2. Generate minimum 5 sections with detailed content.
3. Each section must have at least 3 bullet points.
4. Make content professional, detailed, and valuable.
5. Use the document type to determine structure.
6. Colors must be readable and professional.
7. Never use bright yellow or neon colors as primary.
Use these planned sections where relevant: {', '.join(template['sections'])}. Never invent citations, statistics, names, or sources."""
    response = call_deepseek(system_prompt, f"Create a {document_type} document about: {prompt}")
    clean_response = response.strip()
    if clean_response.startswith("```"):
        clean_response = clean_response.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
    try:
        content = json.loads(clean_response)
        if not isinstance(content.get("sections"), list):
            raise ValueError("sections is missing")
        return content
    except (json.JSONDecodeError, ValueError, AttributeError):
        return {
            "title": document_type.title(), "subtitle": prompt[:160], "author": "AOS - AI Operating System", "date": date.today().isoformat(),
            "design": {"primary_color": "#1a1a2e", "accent_color": "#667eea", "secondary_color": "#16213e", "background_color": "#ffffff", "text_color": "#1f2937", "font_style": "modern", "layout_style": "corporate"},
            "sections": [{"heading": "Generated Content", "content": response, "subsections": [], "bullet_points": [], "has_table": False, "table_data": []}],
            "footer_text": "Confidential document generated by AOS",
        }


def create_pdf_file(content: dict, filename: str) -> str:
    design = content.get("design", {})
    primary_hex = str(design.get("primary_color", "#1a1a2e")).lstrip("#")
    accent_hex = str(design.get("accent_color", "#667eea")).lstrip("#")
    secondary_hex = str(design.get("secondary_color", "#16213e")).lstrip("#")

    def color_or_default(value: str, fallback: str) -> HexColor:
        try:
            return HexColor("#" + value)
        except (TypeError, ValueError):
            return HexColor(fallback)

    primary = color_or_default(primary_hex, "#1a1a2e")
    accent = color_or_default(accent_hex, "#667eea")
    secondary = color_or_default(secondary_hex, "#16213e")
    text_color = HexColor("#1f2937")
    bg_color = HexColor("#ffffff")
    heading_font_size = 24
    body_font_size = 11
    filepath = os.path.join(OUTPUT_DIRECTORY, f"{filename}.pdf")
    document = SimpleDocTemplate(filepath, pagesize=A4, rightMargin=2 * cm, leftMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("AOSTitle", parent=styles["Title"], fontSize=heading_font_size + 8, textColor=primary, alignment=TA_CENTER, spaceAfter=12, fontName="Helvetica-Bold")
    subtitle_style = ParagraphStyle("AOSSubtitle", parent=styles["Normal"], fontSize=heading_font_size - 4, textColor=secondary, alignment=TA_CENTER, spaceAfter=6, fontName="Helvetica")
    heading1_style = ParagraphStyle("AOSHeading1", parent=styles["Heading1"], fontSize=heading_font_size, textColor=primary, spaceBefore=16, spaceAfter=8, fontName="Helvetica-Bold")
    heading2_style = ParagraphStyle("AOSHeading2", parent=styles["Heading2"], fontSize=heading_font_size - 4, textColor=secondary, spaceBefore=12, spaceAfter=6, fontName="Helvetica-Bold")
    body_style = ParagraphStyle("AOSBody", parent=styles["BodyText"], fontSize=body_font_size, textColor=text_color, backColor=bg_color, spaceBefore=4, spaceAfter=8, leading=16, alignment=TA_JUSTIFY, fontName="Helvetica")
    bullet_style = ParagraphStyle("AOSBullet", parent=body_style, leftIndent=20, spaceBefore=2, spaceAfter=2)
    story = [Paragraph(str(content.get("title", "AOS Document")), title_style), Paragraph(str(content.get("subtitle", "")), subtitle_style), Paragraph(f"{content.get('author', 'AOS - AI Operating System')}  |  {content.get('date', date.today().isoformat())}", subtitle_style), HRFlowable(width="100%", thickness=2, color=accent), Spacer(1, 16)]
    for section in content.get("sections", []):
        story.append(Paragraph(str(section.get("heading", "Section")), heading1_style))
        story.append(Paragraph(str(section.get("content", "")), body_style))
        for subsection in section.get("subsections", []) or []:
            story.append(Paragraph(str(subsection.get("heading", "")), heading2_style))
            story.append(Paragraph(str(subsection.get("content", "")), body_style))
        for bullet in section.get("bullet_points", []) or []:
            story.append(Paragraph(f"• {bullet}", bullet_style))
        table_data = section.get("table_data", []) or []
        if section.get("has_table") and table_data:
            table = Table(table_data, repeatRows=1)
            table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), primary), ("TEXTCOLOR", (0, 0), (-1, 0), white), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("BACKGROUND", (0, 1), (-1, -1), bg_color), ("GRID", (0, 0), (-1, -1), 0.5, accent), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("PADDING", (0, 0), (-1, -1), 7)]))
            story.extend([Spacer(1, 8), table])
        story.append(Spacer(1, 12))
    document.build(story)
    return filepath


@router.post("/api/generate-pdf")
async def generate_pdf(request: PDFRequest):
    try:
        document_type = request.document_type or "general"
        lower_type = document_type.lower()
        if "research" in lower_type:
            template = TEMPLATES["research_paper"]
        elif "resume" in lower_type:
            template = TEMPLATES["resume"]
        elif "invoice" in lower_type:
            template = TEMPLATES["invoice"]
        elif "proposal" in lower_type:
            template = TEMPLATES["proposal"]
        else:
            template = TEMPLATES["business_report"]
        content = generate_pdf_content(request.prompt, document_type, template)
        filename = f"aos_document_{uuid.uuid4().hex[:8]}"
        filepath = create_pdf_file(content, filename)
        safe_name = ''.join(char if char.isalnum() or char in (' ', '-', '_') else '' for char in str(content.get('title', 'document'))).strip() or 'document'
        return FileResponse(filepath, media_type="application/pdf", filename=f"{safe_name}.pdf")
    except HTTPException:
        raise
    except Exception as error:
        raise HTTPException(status_code=500, detail=str(error)) from error
