from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel
from docx import Document
from docx.shared import Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import os
import sys
import uuid
import json
import requests
from datetime import date

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from main import call_deepseek

router = APIRouter()
OUTPUT_DIRECTORY = "output"
os.makedirs(OUTPUT_DIRECTORY, exist_ok=True)


class WordRequest(BaseModel):
    prompt: str
    document_type: str = "general"


def _extract_json(response: str) -> dict:
    start, end = response.find("{"), response.rfind("}")
    if start < 0 or end <= start:
        raise ValueError("No JSON object returned")
    return json.loads(response[start:end + 1])


def generate_word_content(prompt: str, document_type: str) -> dict:
    system_prompt = """You are an expert document writer and Microsoft Word designer.
Return ONLY valid JSON with title, subtitle, author, date, primary_color, accent_color, sections, and footer_text.
Each section must contain heading, content (at least four useful sentences), bullet_points, subsections,
has_table, table_headers, and table_rows. Generate a minimum of five detailed professional sections.
Choose readable six-character hexadecimal colors without # which fit the topic. Never invent sources or statistics."""
    response = call_deepseek(system_prompt, f"Create a {document_type} Word document about: {prompt}")
    try:
        content = _extract_json(response)
        if not isinstance(content.get("sections"), list):
            raise ValueError("sections missing")
        return content
    except (ValueError, json.JSONDecodeError, TypeError):
        return {
            "title": document_type.title(), "subtitle": prompt[:160], "author": "AOS - AI Operating System", "date": date.today().isoformat(),
            "primary_color": "1e3a8a", "accent_color": "3b82f6", "footer_text": "Generated by AOS AI Operating System",
            "sections": [{"heading": "Generated Content", "content": response, "bullet_points": [], "subsections": [], "has_table": False, "table_headers": [], "table_rows": []}],
        }


def hex_to_rgb(hex_color: str) -> RGBColor:
    value = str(hex_color or "1e3a8a").lstrip("#")
    if len(value) != 6 or any(char not in "0123456789abcdefABCDEF" for char in value):
        value = "1e3a8a"
    return RGBColor(int(value[0:2], 16), int(value[2:4], 16), int(value[4:6], 16))


def _line(document: Document, color: str) -> None:
    paragraph = document.add_paragraph()
    border = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "8")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), str(color).lstrip("#"))
    border.append(bottom)
    paragraph._p.get_or_add_pPr().append(border)
    paragraph.paragraph_format.space_after = Pt(8)


def _cell_fill(cell, color: str) -> None:
    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), str(color).lstrip("#"))
    cell._tc.get_or_add_tcPr().append(shading)


def create_word_file(content: dict, filename: str) -> str:
    filepath = os.path.join(OUTPUT_DIRECTORY, f"{filename}.docx")
    primary_hex = str(content.get("primary_color", "1e3a8a")).lstrip("#")
    accent_hex = str(content.get("accent_color", "3b82f6")).lstrip("#")
    primary_rgb, accent_rgb = hex_to_rgb(primary_hex), hex_to_rgb(accent_hex)
    document = Document()
    for section in document.sections:
        section.top_margin = section.bottom_margin = Cm(2.5)
        section.left_margin = section.right_margin = Cm(2.5)

    for _ in range(2): document.add_paragraph()
    title = document.add_paragraph(); title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(str(content.get("title", "Document"))); run.font.size = Pt(28); run.font.bold = True; run.font.color.rgb = primary_rgb
    subtitle = str(content.get("subtitle", ""))
    if subtitle:
        paragraph = document.add_paragraph(); paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = paragraph.add_run(subtitle); run.font.size = Pt(16); run.font.color.rgb = accent_rgb
    meta = document.add_paragraph(); meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = meta.add_run(f"{content.get('author', 'AOS')}  |  {content.get('date', date.today().isoformat())}"); run.font.size = Pt(10); run.font.color.rgb = RGBColor(136, 136, 136)
    _line(document, primary_hex); document.add_page_break()

    for index, section in enumerate(content.get("sections", []), 1):
        heading = document.add_paragraph(); run = heading.add_run(f"{index:02d}.  {section.get('heading', 'Section')}")
        run.font.size = Pt(16); run.font.bold = True; run.font.color.rgb = primary_rgb
        heading.paragraph_format.space_before = Pt(16); heading.paragraph_format.space_after = Pt(8)
        _line(document, accent_hex)
        if section.get("content"):
            paragraph = document.add_paragraph(str(section["content"])); paragraph.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY; paragraph.paragraph_format.line_spacing = Pt(16)
            for run in paragraph.runs: run.font.size = Pt(11); run.font.color.rgb = RGBColor(31, 41, 55)
        for bullet in section.get("bullet_points", []) or []:
            paragraph = document.add_paragraph(style="List Bullet"); run = paragraph.add_run(str(bullet)); run.font.size = Pt(11); run.font.color.rgb = RGBColor(31, 41, 55)
        for subsection in section.get("subsections", []) or []:
            if subsection.get("heading"):
                paragraph = document.add_paragraph(); run = paragraph.add_run(str(subsection["heading"])); run.font.size = Pt(13); run.font.bold = True; run.font.color.rgb = accent_rgb
            if subsection.get("content"):
                paragraph = document.add_paragraph(str(subsection["content"])); paragraph.paragraph_format.left_indent = Cm(.5)
                for run in paragraph.runs: run.font.size = Pt(11)
        headers, rows = section.get("table_headers", []) or [], section.get("table_rows", []) or []
        if section.get("has_table") and headers and rows:
            table = document.add_table(rows=1 + len(rows), cols=len(headers)); table.style = "Table Grid"
            for column, header in enumerate(headers):
                cell = table.rows[0].cells[column]; cell.text = str(header); _cell_fill(cell, primary_hex)
                for run in cell.paragraphs[0].runs: run.font.bold = True; run.font.color.rgb = RGBColor(255, 255, 255)
            for row_index, row in enumerate(rows):
                for column, value in enumerate(row[:len(headers)]):
                    cell = table.rows[row_index + 1].cells[column]; cell.text = str(value); _cell_fill(cell, "f8fafc" if row_index % 2 == 0 else "ffffff")
        document.add_paragraph()

    document.add_page_break(); ending = document.add_paragraph(); ending.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = ending.add_run(str(content.get("footer_text", "Generated by AOS - AI Operating System"))); run.font.size = Pt(16); run.font.bold = True; run.font.color.rgb = primary_rgb
    document.save(filepath)
    return filepath


@router.post("/api/generate-word")
async def generate_word(request: WordRequest):
    try:
        content = generate_word_content(request.prompt, request.document_type)
        filepath = create_word_file(content, f"aos_word_{uuid.uuid4().hex[:8]}")
        title = "".join(char for char in str(content.get("title", "document")) if char.isalnum() or char in (" ", "-", "_")) or "document"
        return FileResponse(filepath, media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document", filename=f"{title}.docx")
    except HTTPException:
        raise
    except Exception as error:
        raise HTTPException(status_code=500, detail=str(error)) from error
