import json
from datetime import date

def generate_document_json(prompt: str, category: str, layout_style: str, color_palette: str) -> dict:
    from main import call_deepseek
    """Generate structured document JSON content using DeepSeek."""
    system_prompt = f"""You are a professional document writer and UI designer.
Generate highly comprehensive and beautifully structured document content based on the user's prompt.
The document category is "{category}". The layout style is "{layout_style}". The color palette is "{color_palette}".

You MUST return ONLY valid JSON with this exact structure:
{{
  "title": "Main Document Title",
  "subtitle": "Sub-title or brief description",
  "author": "AOS AI Document Studio",
  "date": "{date.today().isoformat()}",
  "category": "{category}",
  "layout_style": "{layout_style}",
  "color_palette": "{color_palette}",
  "sections": [
    {{
      "heading": "Section Heading",
      "paragraphs": [
        "Paragraph 1 containing at least 4 detailed sentences.",
        "Paragraph 2 containing at least 3 detailed sentences."
      ],
      "layout_type": "standard", 
      "list_items": [],
      "quote_text": "",
      "quote_author": "",
      "timeline_items": [],
      "table_headers": [],
      "table_rows": [],
      "chart_type": "",
      "chart_title": "",
      "chart_labels": [],
      "chart_values": [],
      "code_content": "",
      "code_language": "",
      "cards": []
    }}
  ],
  "references": [
    "Reference item 1",
    "Reference item 2"
  ]
}}

Rules for layouts:
- Use "standard" for normal reading sections.
- Use "highlight_box" for sections emphasizing a key fact or warning (paragraphs will be styled in a box with a colored left border).
- Use "quote_card" to showcase a prominent statement/quote. Set "quote_text" and optionally "quote_author".
- Use "timeline" for chronological events, logs, histories, or step-by-step processes. Populate "timeline_items" as array of objects: {{"time": "Q1 2026", "description": "Details..."}}.
- Use "table" for comparing data or structured numbers. Populate "table_headers" and "table_rows".
- Use "chart" to visualize quantitative trends. Set "chart_type" ("bar", "pie", or "line"), "chart_title", "chart_labels" (array of strings), and "chart_values" (array of numbers).
- Use "code_block" ONLY if the user prompt explicitly requests programming code, CLI commands, scripts, or query syntax. NEVER use "code_block" to describe templates, design specifications, or structural lists. For descriptive text and lists, use "standard", "highlight_box", or "information_cards" layouts instead.
- Use "information_cards" for list of items/features. Populate "cards" as array of objects: {{"title": "Card Title", "content": "Card text details..."}}.

Ensure you generate a minimum of 4-6 detailed sections appropriate for a professional "{category}". Make the content extremely rich, informative, and complete. Avoid placeholders or truncated sentences."""

    response = call_deepseek(system_prompt, f"Generate professional content for: {prompt}")
    clean_response = response.strip()
    if clean_response.startswith("```"):
        clean_response = clean_response.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
        
    try:
        content = json.loads(clean_response)
        # Ensure correct schema structure is present
        if not isinstance(content.get("sections"), list):
            raise ValueError("Invalid format: sections is not a list")
        return content
    except Exception as e:
        print("Failed to parse JSON from DeepSeek, generating fallback structured JSON:", e)
        # Fallback structured JSON content
        return {
            "title": f"{category} - Document Studio",
            "subtitle": f"Generated plan based on: {prompt[:120]}",
            "author": "AOS AI Document Studio",
            "date": date.today().isoformat(),
            "category": category,
            "layout_style": layout_style,
            "color_palette": color_palette,
            "sections": [
                {
                    "heading": "Overview",
                    "paragraphs": ["This document was generated by the AOS dynamic template engine based on your request. Below is a structured presentation of the content created by the language model."],
                    "layout_type": "standard",
                    "list_items": [],
                    "quote_text": "",
                    "quote_author": "",
                    "timeline_items": [],
                    "table_headers": [],
                    "table_rows": [],
                    "chart_type": "",
                    "chart_title": "",
                    "chart_labels": [],
                    "chart_values": [],
                    "code_content": "",
                    "code_language": "",
                    "cards": []
                },
                {
                    "heading": "Raw Content Output",
                    "paragraphs": ["An error occurred while generating the parsed structured layout. The raw text response from the assistant is printed below."],
                    "layout_type": "highlight_box",
                    "list_items": [],
                    "quote_text": "",
                    "quote_author": "",
                    "timeline_items": [],
                    "table_headers": [],
                    "table_rows": [],
                    "chart_type": "",
                    "chart_title": "",
                    "chart_labels": [],
                    "chart_values": [],
                    "code_content": "",
                    "code_language": "",
                    "cards": []
                },
                {
                    "heading": "Raw Text",
                    "paragraphs": [],
                    "layout_type": "code_block",
                    "list_items": [],
                    "quote_text": "",
                    "quote_author": "",
                    "timeline_items": [],
                    "table_headers": [],
                    "table_rows": [],
                    "chart_type": "",
                    "chart_title": "",
                    "chart_labels": [],
                    "chart_values": [],
                    "code_content": response,
                    "code_language": "text",
                    "cards": []
                }
            ],
            "references": []
        }

from .analyzer import analyze_document_type
from .template_engine import build_html_document
from .renderer import render_html_to_pdf

def generate_professional_pdf(prompt: str, doc_type_override: str = None) -> tuple:
    """Orchestrate the entire professional PDF generation pipeline.
    
    Returns:
        (filepath, title)
    """
    analysis = analyze_document_type(prompt)
    if doc_type_override and doc_type_override.lower() not in {"pdf", "general"}:
        analysis["category"] = doc_type_override
        
    category = analysis["category"]
    layout_style = analysis["layout_style"]
    color_palette = analysis["color_palette"]
    
    print(f"Document analysis result: Category='{category}', Style='{layout_style}', Palette='{color_palette}'")
    
    doc_json = generate_document_json(prompt, category, layout_style, color_palette)
    html_content = build_html_document(doc_json)
    
    title = doc_json.get("title", "AOS Document")
    filepath = render_html_to_pdf(html_content, title, category)
    
    return filepath, title
