const puppeteer = require('puppeteer');
const path = require('path');

(async () => {
  try {
    const args = process.argv.slice(2);
    if (args.length < 4) {
      console.error('Usage: node render.js <inputHtmlPath> <outputPdfPath> <title> <category>');
      process.exit(1);
    }

    const inputHtmlPath = args[0];
    const outputPdfPath = args[1];
    const title = args[2] || 'AOS Document';
    const category = args[3] || 'General';

    const launchOptions = {
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    };
    if (process.env.PUPPETEER_EXECUTABLE_PATH) {
      launchOptions.executablePath = process.env.PUPPETEER_EXECUTABLE_PATH;
    } else if (process.platform === 'linux') {
      const { execSync } = require('child_process');
      let chromiumPath = 'chromium';
      try {
        chromiumPath = execSync('which chromium').toString().trim();
      } catch (e) {
        try {
          chromiumPath = execSync('which google-chrome').toString().trim();
        } catch (err) {
          const commonPaths = [
            '/usr/bin/chromium',
            '/usr/bin/chromium-browser',
            '/usr/bin/google-chrome',
            '/usr/bin/google-chrome-stable'
          ];
          for (const p of commonPaths) {
            if (require('fs').existsSync(p)) {
              chromiumPath = p;
              break;
            }
          }
        }
      }
      launchOptions.executablePath = chromiumPath;
    }

    const browser = await puppeteer.launch(launchOptions);

    const page = await browser.newPage();
    
    // Load the HTML file
    const fileUrl = 'file://' + path.resolve(inputHtmlPath);
    await page.goto(fileUrl, {
      waitUntil: 'networkidle0',
      timeout: 30000
    });

    // Short wait to ensure Chart.js completely draws the canvas (without animation, it's instant)
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Print to PDF
    await page.pdf({
      path: outputPdfPath,
      format: 'A4',
      printBackground: true,
      displayHeaderFooter: true,
      headerTemplate: `
        <div style="font-size: 8px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; width: 100%; margin-left: 15mm; margin-right: 15mm; display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding-bottom: 5px; color: #94a3b8;">
          <span style="font-weight: 600;">${title}</span>
          <span>${category}</span>
        </div>
      `,
      footerTemplate: `
        <div style="font-size: 8px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; width: 100%; margin-left: 15mm; margin-right: 15mm; display: flex; justify-content: space-between; border-top: 1px solid #f1f5f9; padding-top: 5px; color: #94a3b8;">
          <span>Confidential - Generated by AOS Studio</span>
          <span><span class="pageNumber"></span> / <span class="totalPages"></span></span>
        </div>
      `,
      margin: {
        top: '25mm',
        bottom: '20mm',
        left: '15mm',
        right: '15mm'
      }
    });

    await browser.close();
    console.log('PDF rendered successfully to: ' + outputPdfPath);
    process.exit(0);
  } catch (error) {
    console.error('Puppeteer rendering failed:', error);
    process.exit(1);
  }
})();
